# Generated by Django 3.0.5 on 2020-05-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='paradig',
            new_name='paradigm',
        ),
    ]
